---
- name: Installing and Setting up dnscrypt-proxy
  hosts: all
  become: yes
  vars:


  tasks:
   - name: Install dnscrypt-proxy
     ansible.builtin.apt:
      name: dnscrypt-proxy
      state: present
      update_cache: yes
      cache_valid_time: 3600

   - name: Ensure dnscrypt-proxy is installed
     ansible.builtin.apt:
      name: dnscrypt-proxy
      state: present

   - name: Get installed dnscrypt version
     ansible.builtin.command: dnscrypt-proxy -version
     register: dnscrypt_version
     changed_when: false

   - name: Generate dnscrypt-proxy.toml from Template
     ansible.builtin.template:
      src: templates/dnscrypt-proxy.toml.j2
      dest: /etc/dnscrypt-proxy/dnscrypt-proxy.toml
      owner: root
      group: root
      mode: '0644'
     notify: Enable and Start dnscrypt-proxy

  handlers:
   - name: Enable and Start dnscrypt-proxy
     ansible.builtin.systemd:
      name: dnscrypt-proxy
      enabled: yes
      state: restarted
