- name: Security Playbook - Disable Password Auth, Removing Backdoors
  hosts: all
  become: yes #run as root

  tasks:
   - name: Disable Standard PasswordAuthentication
     ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^#?PasswordAuthentication'
      line: 'PasswordAuthentication no'
      state: present
     notify: Restart SSH

   - name: Disable KbdInteractiveAuthentication (PAM trap door)
     ansible.builtin.lineinfile:
       path: /etc/ssh/sshd_config
       regexp: '^#?KbdInteractiveAuthentication'
       line: 'KbdInteractiveAuthentication no'
       state: present
     notify: Restart SSH

   - name: Nuke cloud-init drop-in overrides (if exist)
     ansible.builtin.file:
       path: /etc/ssh/sshd_config.d/50-cloud-init.conf
       state: absent
     notify: Restart SSH

   - name: Remove public SSH access rule from UFW
     community.general.ufw:
      rule: allow
      port: '22'
      proto: tcp
      src: 'Anywhere'
      delete: yes

   - name: Harden UFW to only let traffic from the itnernal network via WireGuard subnet
     community.general.ufw:
      rule: allow
      port: '22'
      proto: tcp
      src: '10.0.0.0/24'

   - name: Install fail2ban (Defense in Depth)
     ansible.builtin.apt:
      name: fail2ban
      state: present
      update_cache: yes

   - name: Configure fail2ban jail.local for SSH
     ansible.builtin.copy:
      dest: /etc/fail2ban/jail.local
      content: |
       [DEFAULT]
       bantime = 3600
       findtime = 360
       maxretry = 3
       banaction = ufw

       [sshd]
       enabled = true
       port = 22
       filter = sshd
       logpath = /var/log/auth.log
       maxretry = 3
      mode: '0644'
     notify: Restart fail2ban

  handlers:
   - name: Restart SSH
     ansible.builtin.service:
      name: ssh
      state: restarted

   - name: Restart UFW
     ansible.builtin.service:
      name: ufw
      state: restarted

   - name: Restart fail2ban
     ansible.builtin.service:
      name: fail2ban
      state: restarted
